### ISSUE TITLE
Add ENTRYPOINT support

### ISSUE THREAD

**Issue by antoinetran** [interTwin-eu/interlink-slurm-plugin#32]
# Short Description of the issue

When running a container image without /bin/sh inside, then InterLink Slurm Plugin runs the container and fails with
 ```
2024/10/15 16:18:29  info unpack layer: sha256:b1b8049e9ec8c6b64203da2c97a5d0d1d68587e6547287797095a519dfb3e39d
INFO:    Creating SIF file...
FATAL:   stat /bin/sh: no such file or directory
```

## Environment

- Operating System:
- Other related components versions:

## Steps to reproduce

Run an Argo helloworld step.

## Logs, stacktrace, or other symptoms

job.sh
```shell
singularity exec --containall --nv --bind /home/lisaddpc/.interlink/workflows_workspace/globalfitmock-lsdsharedfs-template-hswtg:/work   --bind /home/lisaddpc/.interlink/argo-workflows-5dbdb82f-cbca-40fa-b2fe-89b9cf5deb9f/emptyDirs/var-run-argo:/var/run/argo:rw  --bind /home/lisaddpc/.interlink/argo-workflows-5dbdb82f-cbca-40fa-b2fe-89b9cf5deb9f/command_init.sh:/tmp/command_init.sh --bind /home/lisaddpc/.interlink/argo-workflows-5dbdb82f-cbca-40fa-b2fe-89b9cf5deb9f/args_init.sh:/tmp/args_init.sh docker://quay.io/argoproj/argoexec:v3.5.4 /bin/sh /tmp/command_init.sh &> /home/lisaddpc/.interlink/argo-workflows-5dbdb82f-cbca-40fa-b2fe-89b9cf5deb9f/init.out; echo $? > /home/lisaddpc/.interlink/argo-workflows-5dbdb82f-cbca-40fa-b2fe-89b9cf5deb9f/init.status
# and same for wait and main container
```

# Summary of proposed changes

**Comment by dciangot** [comment]
Bin/sh is used to build the command executed by Singularity (that does not know the entrypoints of the containers).

What is your proposal then exactly?

**Comment by antoinetran** [comment]
I will illustrate my proposition with examples using a docker image that does not contains `/bin/sh`, but contains one entrypoint but no command:
```
podman history quay.io/argoproj/argoexec:v3.5.4
ID            CREATED        CREATED BY                                     SIZE        COMMENT
335e6412fad1  9 months ago   ENTRYPOINT ["argoexec"]                        0 B         buildkit.dockerfile.v0
```

It is a bit simple and complex. Docker image can contain entrypoint and command, only entrypoint, only command, or nothing. Kubernetes yaml can be described to run a container, and override either entrypoint (with "command" field, which is a bit confusing), command (with "args" field), both, nothing.

1. case no override of entrypoint nor command in kubernetes yaml, then interlink should just run singularity with run argument, which will run the image default entrypoint/command similar to what kubernetes container engine would do.


Yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template: # create pods using pod definition in this template
    spec:
      containers:
      - name: helloworld
        image: quay.io/argoproj/argoexec:v3.5.4
        #command: [ "sleep", "10" ]
```

```
podman run --rm quay.io/argoproj/argoexec:v3.5.4
argoexec is the executor sidecar to workflow containers
```

OCI Container are converted to Singularity SIF with entrypoint/command translated to runscript field:
https://docs.sylabs.io/guides/3.6/user-guide/definition_files.html#runscript
Then `singularity run` will execute the runscript if present. So to reproduce the same output as podman beyond:

=> this is what InterLink Slurm should run:
```
singularity run docker://quay.io/argoproj/argoexec:v3.5.4
INFO:    Using cached SIF image
argoexec is the executor sidecar to workflow containers
```

2. case only entrypoint is specified in Kubernetes yaml

Yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template: # create pods using pod definition in this template
    spec:
      containers:
      - name: helloworld
        image: quay.io/argoproj/argoexec:v3.5.4
        command: [ "/etc/passwd"]
```

=> InterLink Slurm should run:
```
singularity exec docker://quay.io/argoproj/argoexec:v3.5.4 /etc/passwd
INFO:    Using cached SIF image
FATAL:   permission denied
```
I run a `/etc/passwd`, which is not an executable, on purpose, to show that we can run something which is not `/bin/sh`, nor the default command. The "permission denied" is the expected stderr here.

3. case only command is specified in Kubernetes yaml

Yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template: # create pods using pod definition in this template
    spec:
      containers:
      - name: helloworld
        image: quay.io/argoproj/argoexec:v3.5.4
        #command: [ "argoexec"]
        args: [ "--log-format", "json", "version" ]
```

=> InterLink Slurm should run:
```
singularity run docker://quay.io/argoproj/argoexec:v3.5.4 argoexec --log-format json version
INFO:    Using cached SIF image
argoexec: v3.5.4
```
4. case entrypoint and command(s) are specified in Kubernetes yaml

Yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template: # create pods using pod definition in this template
    spec:
      containers:
      - name: helloworld
        image: quay.io/argoproj/argoexec:v3.5.4
        command: [ "argoexec"]
        args: [ "--log-format", "json", "version" ]
```

=> InterLink Slurm should run:
```
 singularity exec docker://quay.io/argoproj/argoexec:v3.5.4 argoexec --log-format json version
INFO:    Using cached SIF image
argoexec: v3.5.4
```

5. case entrypoint and command(s) are specified in Kubernetes yaml in complex way with array and quote

Yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template: # create pods using pod definition in this template
    spec:
      restartPolicy: Never
      containers:
      - name: helloworld
        image: alpine
        command:
          - /bin/sh
          # This "-x" quote is interpreted by yaml, not by bash
          - "-x"
          - "-c"
        args:
          - |
            echo "multiline \"script line1"
            echo multiline script line2

```
If we run this in Kubernetes, we have
```
multiline "script line1
multiline script line2
+ echo 'multiline "script line1'
+ echo multiline script line2
```

=> InterLink Slurm should run:
```
singularity exec docker://alpine /bin/sh -x -c "echo \"multiline script line1\";echo multiline script line2"
INFO:    Using cached SIF image
+ echo 'multiline script line1'
multiline script line1
+ echo multiline script line2
multiline script line2
```
